version: "2"
services:
  cvs-tsk-cert-gen-init:
    container_name: cvs-tsk-cert-gen-init
    build: .
    depends_on:
     - sqs
    links:
      - sqs
    environment:
      WAIT_HOSTS: sqs:9324
  sqs:
    container_name: sqs
    image: roribio16/alpine-sqs:latest
    volumes:
      - ./sqs.conf:/opt/custom/elasticmq.conf
    ports:
    - "9324:9324"
    - "9325:9325" # Web interface
