service: cvs-tsk-cert-gen-init

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  tracing:
    lambda: true # enable tracing
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "xray:PutTraceSegments"
            - "xray:PutTelemetryRecords"
          Resource:
            - "*"

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-tracing

functions:
  main:
    handler: src/handler.handler
    events:
      - stream:
          batchSize: 100
          startingPosition: LATEST
          enabled: true
